### PR TITLE
Submission backend challenge - Dio Riandika

### PR DESCRIPTION
**Pull request by diorndk**
Dear @oddle-developer,

Please review the PR

Thank you

### CODE REVIEW

**Comment by oddle-developer** [comment]
@diorndk Thanks for your submission. We will review and get back to you in case of question

**Comment by oddle-developer** [comment]
@diorndk Hi. We didn't see the implemenation for this user story "As an API contributor, I should be able to make sure my contribution won’t break existing function", can you explain in the comment (no need to code) how you plan to ensure this?

**Comment by diorndk** [comment]
Hi @oddle-developer. regarding that story, I'll ensure to implement tests every time I make a changes to code.

**Comment by oddle-developer** [comment]
Thanks for taking time for the assignment

**Pull request closed without merging**
